[package]
name = "portus"
version = "0.1.0"
description = "Activity Monitor for your dev stack."
authors = ["phi"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "portus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
listeners = "0.5.1"
sysinfo = "0.39.3"
bollard = "0.21.0"
thiserror = "2.0.18"
tauri-plugin-positioner = { version = "2.3.2", features = ["tray-icon"] }
specta = "2.0.0-rc.25"
tauri-specta = { version = "2.0.0-rc.25", features = ["derive", "typescript"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "time", "sync"] }

[dev-dependencies]
libc = "0.2.186"
