// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setActive: () => __TAURI_INVOKE<void>("set_active"),
	setIdle: () => __TAURI_INVOKE<void>("set_idle"),
};

/** Events */
export const events = {
	snapshot: makeEvent<Snapshot>("snapshot"),
};

/* Types */
export type AddressFamily = "V4" | "V6";

export type BindScope = "AllInterfaces" | "Loopback" | "Specific";

export type DockerContainer = {
	id: string,
	names: string[],
	image: string,
	state: string,
	status: string,
};

export type DockerSnapshot = {
	status: DockerStatus,
	containers: DockerContainer[],
};

export type DockerStatus = "detected" | "not_detected";

export type PortOwner = {
	pid: number,
	name: string,
	path: string,
};

export type PortRow = {
	protocol: Protocol,
	port: number,
	scope: BindScope,
	specific_addr: string | null,
	families: AddressFamily[],
	owners: PortOwner[],
	key: string,
};

export type ProcessInfo = {
	pid: number,
	parent_pid: number | null,
	name: string,
	command: string[],
	executable: string | null,
	cwd: string | null,
	start_time: number,
	cpu_usage: number | null,
	memory_bytes: number,
};

export type Protocol = "Tcp";

export type Snapshot = {
	ports: SnapshotSection<PortRow[]>,
	processes: SnapshotSection<ProcessInfo[]>,
	docker: SnapshotSection<DockerSnapshot>,
};

export type SnapshotSection<T> = {
	data: T,
	error: string | null,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

