// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setActive: () => __TAURI_INVOKE<void>("set_active"),
	setIdle: () => __TAURI_INVOKE<void>("set_idle"),
	killProcessTree: (target: KillTarget) => typedError<null, KillProcessError>(__TAURI_INVOKE("kill_process_tree", { target })),
	loadProjects: () => __TAURI_INVOKE<Project[]>("load_projects"),
	suggestTasks: (folder: string) => __TAURI_INVOKE<Task[]>("suggest_tasks", { folder }),
	saveProject: (project: Project) => typedError<Project[], string>(__TAURI_INVOKE("save_project", { project })),
	removeProject: (id: string) => typedError<Project[], string>(__TAURI_INVOKE("remove_project", { id })),
	startTask: (projectId: string, taskId: string) => typedError<null, string>(__TAURI_INVOKE("start_task", { projectId, taskId })),
	stopTask: (pgid: number) => typedError<null, string>(__TAURI_INVOKE("stop_task", { pgid })),
	saveAsCandidates: (listenerPid: number) => typedError<SaveAsCandidate[], string>(__TAURI_INVOKE("save_as_candidates", { listenerPid })),
};

/** Events */
export const events = {
	snapshot: makeEvent<Snapshot>("snapshot"),
};

/* Types */
export type AddressFamily = "V4" | "V6";

export type BindScope = "AllInterfaces" | "Loopback" | "Specific";

export type DockerContainer = {
	id: string,
	names: string[],
	image: string,
	state: string,
	status: string,
};

export type DockerSnapshot = {
	status: DockerStatus,
	containers: DockerContainer[],
};

export type DockerStatus = "detected" | "not_detected";

export type KillProcessError = { kind: "needs_elevated_privileges"; pid: number } | { kind: "process_changed"; pid: number } | { kind: "port_changed"; pid: number; port: number } | { kind: "still_running"; pids: number[] } | { kind: "port_still_listening"; port: number } | { kind: "failed"; message: string };

export type KillTarget = {
	pid: number,
	executable: string | null,
	start_time: number,
	expected_port: number | null,
};

export type Lifecycle = "starting" | "running" | "running_no_port" | "exited" | "crashed";

export type ManagedStatus = {
	project_id: string,
	task_id: string,
	pid: number,
	lifecycle: Lifecycle,
	recent_output: string[],
};

export type PortOwner = {
	pid: number,
	name: string,
	path: string,
};

export type PortRow = {
	protocol: Protocol,
	port: number,
	scope: BindScope,
	specific_addr: string | null,
	families: AddressFamily[],
	owners: PortOwner[],
	key: string,
};

export type ProcessInfo = {
	pid: number,
	parent_pid: number | null,
	name: string,
	command: string[],
	executable: string | null,
	cwd: string | null,
	start_time: number,
	cpu_usage: number | null,
	memory_bytes: number,
};

export type Project = {
	id: string,
	name: string,
	folder: string,
	tasks: Task[],
};

export type Protocol = "Tcp";

export type SaveAsCandidate = {
	pid: number,
	command: string,
	is_shell: boolean,
};

export type Snapshot = {
	ports: SnapshotSection<PortRow[]>,
	processes: SnapshotSection<ProcessInfo[]>,
	docker: SnapshotSection<DockerSnapshot>,
	managed: ManagedStatus[],
};

export type SnapshotSection<T> = {
	data: T,
	error: string | null,
};

export type Task = {
	id: string,
	name: string,
	command: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

